### ISSUE TITLE
Dragging icons sometimes does not work

### ISSUE THREAD

**Issue by kamulos** [jderose9/dash-to-panel#190] opened 2017-06-16 22:36 UTC
This occurs especially often, when trying to drag an icon to the last position (behind the currently last icon). But I also had a case, where an icon refused to be dragged to any position. I hope you can reproduce it.

**Comment by jderose9** [comment] 2017-06-20 02:54
#198 is newer, but I think it illustrates the problem you are describing? Is that correct?

**Comment by kamulos** [comment] 2017-06-20 11:17
Yes, I think those are basically two symptoms of the same bug. I was talking about the reordering of the symbols, not the adding of a symbol.

Regarding the case I mentioned, where an icon could not be repositioned at all: I did not find a way to reproduce it reliably. If it occurs again, I will try to provide more information.

**Comment by jderose9** [comment] 2017-10-25 01:28
I'm going to close this since #198 has the reproduction steps. Thanks!

**Closed by jderose9** 2017-10-25 01:28 UTC
