### ISSUE TITLE
AppMenu Overflowing over the icons

### ISSUE THREAD

**Issue by AdaLiszk** [jderose9/dash-to-panel#143] opened 2017-04-28 21:04 UTC
So when the AppMenu is enabled but a window title is ridiculously long it's overflow on top of the icons and the menu. It would be nice if it will fill the available space or at least the icons will be on the top layer.

![Screenshot](https://lh3.googleusercontent.com/j1dHr_4yEWgfEqxwDsO9ZRh_lz86Pb1aSQ8ogsYg25QszZtz5cFM2eW-k9EiaQlcX9eu8lmLJ1MC5DXY7D_HpNflKqr4ugaWgv5kexJGVee7ozFiW7SOIQTKhmzXQJoP3FSca1TUJX8LBfinF2BJjU1-kXj9qE8XjlLcchin1emRQlxjMkzs3PBXvWqR_tCFZnJzdb193fUG8CtGnnWHXmLa-RUVhr53625HjtckcCPgqbstZqaIt9rxge8c1G2c8eZqeMe7uPEXqbQjhc1JN-7kkZxMyDRxNqAPcceqlD_uvThjHocZ8sKZxFbO8ew0iPdt30CakZZ-6Dtqwg2TnaW0WMSYySsv9M3jiNyPd1Xg3R1sG9_mGwsXRk48p1IUpxyuUsM1HRrGk8iprlT_c45O04AowqX9BGS2MJwF-ERcfPLILAAygIw-IVf6P0lksSvHC75lbwqdlTR-JauQ1C57Cm_LXC22Mx0xDTka5did-EPa-qK-JHgBgsTR8XYj-GjaIVf4S_E_kN7Eg4TNlZiRNEgXdoAV98068xCULYVVBzxPv5CGvS1mXkyq3dpcpx2BXbg_QOww_ggiqneNVu_J8b844O3FoS_pzHHXYiLZmPKD0zLXJEFevjokdSgSR1GP2P70AJqM_v4KjEYONIy-Tf_BxTIImck=w1746-h982-no)

Also if you touch it it would be nice to have option to align it to the left, center, right side of the middle region and add option to hide the icon of the application 🙂

**Comment by SolarLiner** [comment] 2017-04-28 22:02
Duplicate of #110 (as I opened that issue myself). It is annoying, but it is because you're using either Pixel Saver or some other extension that switches the app name with its window title.

**Comment by jderose9** [comment] 2017-04-29 02:46
Yep, as @SolarLiner, please hop over to #110 for updates. Thanks so much for your time in reporting this!

**Closed by jderose9** 2017-04-29 02:46 UTC
Labels: duplicate

**Comment by AdaLiszk** [comment] 2017-04-29 05:06
Oh, sorry for the duplicate, idk why I didn't checked before I submitted 😳
