### ISSUE TITLE
Completed main page

### ISSUE THREAD

**Issue by LinxGem33** [jderose9/dash-to-panel#270] opened 2017-10-25 04:32 UTC
@jderose9 

please see the 95% completed main page for your review before i finish and i send a pull request link is below :+1: 

ive completed the logo the banners and all artwork regarding the project , i shall package all the artwork raw files etc and they are all under a GPLv3 license.

also i used arc menu on the main pic as you was right there was alot of space on the pic and it kinda just looked like a wallpaper.

let me know if you want anything adding or edited ior removed etc or if your happy with the direction before i finish the minor touches.

link - https://github.com/LinxGem33/dash-to-panel

**Comment by Bindea** [comment] 2017-10-25 10:28
Looks awesome. :)

**Comment by lexruee** [comment] 2017-10-25 10:41
Holy moly, this looks awesome! :smiley:

**Comment by jderose9** [comment] 2017-10-25 17:21
This looks really awesome! Thanks so much for the effort. The logos are great, and I really like the animated gif to show the user popups.

Here's my feedback:
1. The text under the logo: The word "new" seems a little arbitrary to me, so I'd rather not use that. I'd also like to not use the word "dock" as there's already confusion between this extension and dash-to-dock. How about "An Icon Taskbar for Gnome Shell" or something along those lines?

2. Primary screenshot: I'm concerned about visual confusion between this extension's landing page and Arc Menu's. Could we use a different wallpaper on the primary screenshot (though, I really like the art style)? Perhaps we can show an open window preview instead of Arc Menu, and then use the existing screenshot further down to call out the integration with arc menu.

3. I love the laptop frame around the Arc Menu screenshot if you are up for including that or something similar.

4. I think the indicator and number overlay sections looks awesome but I'm a little concerned about user confusion as some of these configurations aren't exactly reproducible within the extension settings currently. Specifically, the justified dots and outset dashes, and the red backround for the number overlay bubbles. Is it ok if I tweak these to match actual possible configurations?

5. I'd like to make the link to install from extensions.gnome.org much more prominent. Any ideas on this? Maybe a large icon button?

6. Do you think it's worth adding screenshots to showcase any other features?

7. I'm hoping to make the FAQ section less of a wall-of-text somehow. Any ideas? Maybe just italics on the response or something along those lines.

8. Rather than a rigid "development roadmap" I thought we could add a section describing how to volunteer and listing out some high priority enhancements that don't have anyone assigned.

9. Thoughts on how to incorporate a gallery of user screenshots? (Maybe some of this stuff would be best in the github wiki section.)

10. I'm not very knowledgeable regarding licenses but my understanding is that GPLv2 and GPLv3 are not perfectly compatible. Since this extension derived from GPLv2 work, does that mean that your logo can not be included in the extension settings About menu?

Sorry for the huge list, and thanks again!

**Comment by LinxGem33** [comment] 2017-10-25 17:59
@jderose9 

appreciate the feedback give me a few days and ill rearrange and design some new artwork and edit the things you highlighted in your message and we can take it from there.

i already have a good idea regarding the main pic which im working on which i think you might like as i was also not happy using the main pic as it didn’t really highlight dash to panel but i think what i am working on now hopefully will.

**Comment by jderose9** [comment] 2017-10-25 21:24
@LinxGem33 
Thanks! I can help out as needed on any text/screenshots/etc.. just let me know.

>also if you can give me a list of the priority enhancements that no one is working or not assigned
I've been going through and tagging them `needs volunteer` and `high priority`. I haven't gotten through everything but here's the current list:

[High priority items needing volunteer](https://github.com/jderose9/dash-to-panel/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aopen%20label%3A%22high%20priority%22%20label%3A%22needs%20volunteer%22%20)

**Comment by LinxGem33** [comment] 2017-10-26 13:09
@jderose9 

please see the new and improved main page, it took me a shorter time than i thought.

i have taken your points and edited accordingly as you will see there is new art work which i think highlights dash to panel much better than the previous main art work.

> I'd like to make the link to install from extensions.gnome.org much more prominent. Any ideas on this? Maybe a large icon button?

regarding the installation and using a button i tried this and it didn’t look very nice it just looked odd unfortunately there is only so much you can do with github to make it look nice.

> Thoughts on how to incorporate a gallery of user screen shots? (Maybe some of this stuff would be best in the github wiki section.)

regarding a gallery i have some thoughts on this but this can be done at a later date as would need the screen shots etc 

**final thoughts**
overall i think this hopefully should adress most of the issues you raised regarding the main page and in regards to the FAQs i agree this should really be in the wiki , you can see the updated version by clicking on the link below.

link - https://github.com/LinxGem33/dash-to-panel

**Comment by jderose9** [comment] 2017-10-27 22:28
@LinxGem33

Wow this looks awesome! Great idea on the call-out to the panel within the image. I like main panel image 1 better as well. One other idea I had was to use the image 2 style and push the blue section up above the panel so the status icons are visible and it's more obvious that the taskbar is integration into the main panel.  But I'm not sure if this will look better or not so just use your discretion :)

I still find the text below the logo to be a little confusing an redundant. Maybe it could say "an icon taskbar for gnome she'll" or "integrated taskbar + status panel for gnome"?

I'm a little confused about the alt indicator image. Could we just go back to the prior one?

I'll prob want to tweak the text a little if that's ok but I can do that when you open a PR.

Thanks again so much! Looks great..

**Comment by jderose9** [comment] 2017-10-31 04:14
Thanks so much! I merged this in. I re-arranged some stuff and pulled your features table back in, and trimmed down on some of the text. If I totally ruined any of your work, just tell me.

Also, if you don't mind to provide a slightly darker green version of the checkbox icon, that would be awesome. I thought the previous one was a little too light on some displays, but the new image I replaced it with has a thicker circle so doesn't quite match the planned icon.

Anyway, I really appreciate the effort.. looks much better now. Thank you!!

**Closed by jderose9** 2017-10-31 04:14 UTC

**Comment by LinxGem33** [comment] 2017-11-03 20:42
@jderose9 

sorry about late reply been busy at work, 

yeah sure ill redesign you a new check mark icon with a darker colour just give a day or so.

also i want to design  smaller icons for the indicators as im not happy with them they seem to big if thats ok with you?
