### ISSUE TITLE
Preview window timeout too fast

### ISSUE THREAD

**Issue by xpduyson** [jderose9/dash-to-panel#19] opened 2017-01-11 01:44 UTC
Most of time preview windows disappear before I hover mouse on them. 

Example: https://gfycat.com/CleanPleasingDiamondbackrattlesnake

**Comment by jderose9** [comment] 2017-01-11 17:00
This seems to be due to some gap introduced in the Flat-Plat theme between the popup window and the element it is attached to. The popup window closes as it leaves the icon container if it hasn't entered the popup window and with this gap added it leaves the icon container without immediately entering the popup window.

**Comment by jderose9** [comment] 2017-01-11 17:09
BTW I added a config setting to disable the window previews so that would be an option if you wish to continue using the extension with this theme until the issue is resolved.

**Comment by cra0zy** [comment] 2017-01-11 18:02
This can be easily fixed by just adding a delay to mouse leave event so that it doesn't start hiding the preview window immediately... This is very annoying with any theme.

**Comment by jderose9** [comment] 2017-01-11 18:42
> This can be easily fixed by just adding a delay to mouse leave event so that it doesn't start hiding the preview window immediately... This is very annoying with any theme.

The popups need to be synchronized across app icons or when you enter horizontally the preview from the previous icon will block the popup for the newly entered icon. Also, there is a matter of how much timeout is annoying versus how much is required to solve the issue (which is dependent on the gap and mouse speed). Not impossible but it's not a one-liner.

**Comment by jderose9** [comment] 2017-01-12 04:08
If you guys want to check out the hoverfix branch, I attempted to address this with a timeout. There is an added 100ms delay. But, since the popup consumes the UI and no other events get through while it's open (seems to be a gnome thing), it does feel a bit more laggy when moving from one icon to the other, so I'm hesitant that it's the right solution. Definitely don't think the timeout should be increased beyond the 100ms.. Check it out and let me know if it resolves the issue and what you think.

**Comment by cra0zy** [comment] 2017-01-12 11:13
Just add a slider for extra timeout to the settings.

**Comment by jderose9** [comment] 2017-01-20 15:57
Has anyone been able to try the hoverfix branch?

**Comment by cra0zy** [comment] 2017-01-20 15:58
It worked fine for me.

**Comment by glebsam** [comment] 2017-01-20 17:25
Thank you, extension from the hoverfix branch works great!

**Comment by xpduyson** [comment] 2017-01-21 11:20
hoverfix branch work fine for me.

**Closed** 2017-01-25 04:14 UTC

**Comment by libcg** [comment] 2017-01-26 06:38
I think this bug should be fixed in the theme itself, especially if it degrades the user experience with feeling of lagginess.

**Comment by jderose9** [comment] 2017-01-26 18:34
I did some research and was able to override the grabHelper when the preview window is up and identify when another icon is entered. But, with that solution, if you pass with the mouse in a diagonal direction into the preview and enter an adjacent icon, the preview is still shut. There's no way to know whether the user's intention is to travel into the adjacent icon or across it to get to the preview.

So I decided the timeout was the best solution. It seems to solve both issues (themes with a gap and quickly passing over an adjacent icon). I added an Advanced option button to the Behavior tab in the settings so you can adjust the timeout. I've been using the default 100ms for a week or so and not perceived any lag as I was worried about. It can be set to 0 for the old behavior. This stuff has been merged to master so it will go out in the next update to gnome.org.

I would like to get #26 in too and allow a delay to be configured before the preview pops up, so that would also help with any possibility of lag as the preview won't necessarily need to be popping up on a quick mouse over.
