### ISSUE TITLE
Cycle through windows by scrolling over the application icon

### ISSUE THREAD

**Issue by BeayemX** [jderose9/dash-to-panel#233] opened 2017-08-19 18:56 UTC
At the moment it is only possible to cycle through open windows when clicking on the icon.
Being able to do this instead by scrolling would be a nice addition.

This would make the experience more consistent because it would always show/hide the application when clicking the icon and the behavior would not change depending on if there is only one or if there are multiple windows per application.

**Comment by jderose9** [comment] 2017-09-12 18:46
Hello! Thanks for this. I believe it is a duplicate of #30 though. You can comment there or subscribe to that one for updates.

**Closed by jderose9** 2017-09-12 18:46 UTC
Labels: duplicate
