### ISSUE TITLE
Activities button always comes back despite being turned off in the options

### ISSUE THREAD

**Issue by kristijan-ujevic** [jderose9/dash-to-panel#220] opened 2017-07-29 13:46 UTC
As the title says, 

Turning it on again and then off makes it go away but it comes back the every session/unlocking

What could be the problem?

**Comment by jderose9** [comment] 2017-07-31 17:51
I've seen this happen when I have another extension installed that add the activities button back. Can you try disabling all other extensions and see if this still occurs?

**Comment by jderose9** [comment] 2017-10-25 01:49
Closing as I'm fairly certain this is caused by another extension.

**Closed by jderose9** 2017-10-25 01:49 UTC
