### ISSUE TITLE
Icons and running indicator display after 10-20 sec

### ISSUE THREAD

**Issue by grandixximo** [jderose9/dash-to-panel#146] opened 2017-05-03 06:55 UTC
I have this strange behavior, where i start my terminal and the icon is there, but the running indicator is not, after 10-20 sec the indicator appears, this is not really bothering me, but i notice, then after i open files which are pinned as favorite, and then closing it, the icons themselves of the apps start to appear after 10-20 sec after i actually opened them, at this point disabling dash to panel and the dash has similar behavior, if i restart the shell, i can replicate the problem only if using the panel, the standard dash doesn't create the problem, the problem persists even after disabling dash to panel tough

**Comment by grandixximo** [comment] 2017-05-03 10:23
Maybe i wasn't very accurate in the problem description, what it boils down to is that the icons of the windows do not show up in real time, i have to wait 10-20 sec for them to pop up after the application it's been opened, and sometimes they also do not disappear after a while that the application it's been opened

**Comment by jderose9** [comment] 2017-05-03 16:50
Hi there! Thanks so much for reporting this. I think it is a dupe of #133 / #96 though. Would you mind to hop over to those issues and subscribe for updates? Thanks!

**Closed by jderose9** 2017-05-03 16:50 UTC
