### ISSUE TITLE
Freeze when clicking on window preview while using virtualbox mouse integration

### ISSUE THREAD

**Issue by sw9** [jderose9/dash-to-panel#212] opened 2017-07-16 20:21 UTC
To reproduce this, open up a virtualbox vm with mouse integration enabled. Click inside of the vm, then move the mouse down to the gnome panel. Hover over an application icon, then click on a window preview. The entire gnome shell will become unresponsive. However, clicking on the application icon directly works fine.

**Comment by ensonb** [comment] 2017-07-17 19:06
I'm struggling with this as well , happening in ubuntu-gnome  16.04 , sometimes it happens with remmina , I have to switch to tty2  to restart the gnome-shell. 
As stated by @sw9 , clicking on the icon switch the window, clicking on the preview window above the icon freezes the shell.
tailing the /var/log/syslog to catch an error at the moment of this happening gave me this (not so sure if related):
 
`Gjs-Message: JS LOG: pushModal: invocation of begin_modal failed`

**Comment by franglais125** [comment] 2017-07-17 19:10
I guess this has to do with the grabbing that happens on `_onLeave` (https://github.com/jderose9/dash-to-panel/blob/master/windowPreview.js#L151), and this grabbing competes with the Virtualbox one.

Just curious, does it happen under Wayland?

**Comment by sw9** [comment] 2017-07-17 19:24
@ensonb I've found that pressing the super key and launching overview unfreezes the shell, so that avoids needing to restart gnome-shell. Still annoying though.

**Comment by ensonb** [comment] 2017-07-17 20:10
@franglais125  To me is happening in Xorg (X11). I was convinced it was related to my graphic card.

@sw9  I've learned the super key too, only works for me if the virtual-box doesn't have the mouse captured, in which case i have to release it,  then alt+tab then the super key.

**Comment by franglais125** [comment] 2017-07-17 20:12
@ensonb That's what I was guessing (the problem on X11). I was actually asking if it happens on Wayland *too* :).

**Comment by ensonb** [comment] 2017-07-17 20:42
Yeah , I went up and googled around to try it out because I really love the peek feature of this extension to the level of being   dependant on on it but I think i will postpone the troubleshooting for this one, since I already have a love/hate relationship with this bipolar distro.

![selection_123](https://user-images.githubusercontent.com/2094732/28288697-af45c532-6b05-11e7-97f9-e1a932575284.jpg)

**Comment by franglais125** [comment] 2017-07-17 21:06
I have prepared a tentative fix in https://github.com/franglais125/dash-to-panel/tree/hover_virtual.

Can any of you test it?

**Comment by ensonb** [comment] 2017-07-17 21:35
Tested and worked perfectly.  Thank You very much for this fix. @franglais125

**Comment by franglais125** [comment] 2017-07-17 21:37
I've been working on porting this feature to dash-to-dock, so I'm trying to hunt bugs that could be related. Please let me know if you find regressions that might be due to the fix... I'll open a PR tomorrow or the day after if I find no problems. Also, perhaps @jderose9 has a nicer solution.

Happy it worked for you!

**Comment by jderose9** [comment] 2017-07-17 23:19
@franglais125 Thanks so much as always! I think it would have taken me quite a while to run down this one.

I'm not observing any major issues with your change. However (this is nitpicky), I do see an extra flicker around the window highlight as the focus is re-selected. I'm wondering if we can first check that the focus has been lost first?

`if(!this.actor.has_key_focus())
                this.actor.grab_key_focus();`

This solves the flickering for me (although I'm having trouble repro'ing the original issue in virtualbox so I'm not sure whether that issue is solved).

**Comment by franglais125** [comment] 2017-07-17 23:23
That's great to hear! It's not nit-picky at all, I was actually trying to fix the same (small) issue! I'll give your suggestion a try and see if it's better.

**Comment by sw9** [comment] 2017-07-17 23:28
It's weird that the patch works for @ensonb. I just tried your branch and it didn't make a difference for me.

**Comment by franglais125** [comment] 2017-07-17 23:31
@sw9 I modified the original patch trying to fix the small issue @jderose9 mentioned (flickering). I'll let you know when it's sorted out. Apologies.

**Comment by franglais125** [comment] 2017-07-17 23:36
@sw9 I reverted it back while trying to fix the other smaller problem. Can you test it again? After installing that branch, restart gnome-shell, but also close and reopen VBox.

**Comment by jderose9** [comment] 2017-07-17 23:39
@sw9 You can double check that you've got @franglais125's fix by looking in:
`~/.local/share/gnome-shell/extensions/dash-to-panel@jderose9.github.com/windowPreview.js`

You should see the `this.actor.grab_key_focus();` around Line 155.

Also make sure you have restarted gnome-shell after it's applied.

**Comment by sw9** [comment] 2017-07-17 23:51
Yup, confirmed works for me. I think I see the flickering issue though if we're referring to the same thing. The animation when you re-hover over the icon for the focused application jumps a little.

**Comment by ensonb** [comment] 2017-07-18 00:16
I saw the flashing too but I was thinking it was a feature  :smile:

**Comment by franglais125** [comment] 2017-07-19 20:45
@jderose9 I haven't found a cleaner solution.

In my testing, I can only fix the issue 100% of the times when using `grab_key_focus()` *before* calling the `grabHelper`. But this produces the ugly effect that we were seeing.
When using  `grab_key_focus()` after calling `grabHelper`, the situation is much better, but still not perfect.

I manage to reproduce this quite easily with Gnome Boxes btw, in case you have that. I tried to produce a small video to show the problem, but due to the virtualization the frames are all broken.

**Comment by franglais125** [comment] 2017-07-19 21:55
@all: the good news is that this is not an issue on Wayland (at least on my testing, Gnome 3.22 here).

**Comment by ensonb** [comment] 2017-07-19 22:52
The tentative fix helped me so much, my workflow was being constantly broken by that bug very often, it was very uncomfortable . Will we get this fix from the main branch in the event of updating or you will be still working on a more concrete definitive work around?. If the latter, then I will keep a copy of the windowPreview.js in the meantime.

**Comment by franglais125** [comment] 2017-07-19 22:57
@ensonb Just to be sure: you still have the windows coming into/out of focus when the preview shows up?

**Comment by ensonb** [comment] 2017-07-20 14:21
@franglais125 I beliveve it is, I have recorded a small video just to be sure.

<a href="http://www.youtube.com/watch?feature=player_embedded&v=aunju4e4X9Y
" target="_blank"><img src="http://img.youtube.com/vi/aunju4e4X9Y/0.jpg" 
alt="Dash To Panel Preview" width="240" height="180" border="10" /></a>

**Comment by jderose9** [comment] 2017-07-22 01:01
Has anyone tested that the fix works when experiencing this issue in VirtualBox when checking `if(!this.actor.has_key_focus())` ?

If that can limit the extra flicker to only when the problem occurs rather than for all users then it definitely seems like a reasonable trade-off.

**Comment by sw9** [comment] 2017-07-22 19:37
`if(!this.actor.has_key_focus()) this.actor.grab_key_focus();` solves the virtualbox issue but it doesn't solve flickering. For me, the flickering occurs when focus is moved into and out of the application icon. So the window previews would never be focused right?

**Comment by sw9** [comment] 2017-07-22 23:02
okay, I think I have a solution:
```            this.actor.grab_key_focus();
            this.sourceActor.grab_key_focus();```

Everything seems to work for me and I don't see any flickering.

**Comment by franglais125** [comment] 2017-07-22 23:37
As a reminder, I'm testing Gnome Boxes.

@jderose9 I did test with the `if(!this.actor.has_key_focus())` condition, but it didn't help.

@sw9 your branch didn't help with the flickering in my testing.

At this point I'll stop my posting on this issue, as I'm not sure my input is helping a lot. Of course, if I make any breakthrough I'll let you know, but I'll let the original bug reporters provide the feedback.

**Comment by sw9** [comment] 2017-07-23 00:27
Uploaded some gifs showing the flickering I'm referring to:

Flickering (before):
[https://gfycat.com/gifs/detail/briskbaggylamb](url)

No flickering (after):
[https://gfycat.com/gifs/detail/mistyunpleasantbettong](url)

**Comment by jderose9** [comment] 2017-07-23 17:45
@franglais125 it won't help flickering inside virtual box but it does help when not using it.

**Comment by jderose9** [comment] 2017-07-23 17:56
@sw9 thanks! Is the first line actually necessary?

**Comment by sw9** [comment] 2017-07-23 18:31
@jderose9 good point, works for me with just the second line actually. updated.

**Comment by sw9** [comment] 2017-07-23 18:55
alright, found one more issue. it looks focus isn't transferred to the selected window after clicking the preview.

**Comment by jderose9** [comment] 2017-07-23 20:04
Maybe try swapping your two lines so the focus lands on the targeted window?

**Comment by sw9** [comment] 2017-07-23 21:35
Alright, so it looks like I have to give up on this bug, because I just don't see a way to get it to work.

To summarize what I've learned, basically, the line `this.sourceActor.grab_key_focus();` is equivalent to doing Ctrl-Alt-Tab and focusing the "top bar". This results in the problem that if you move the mouse cursor to an application icon and then move it off the panel, that application icon will remain selected (because this is how navigation with the arrow keys work). Also, if you select a window preview, the panel will still be focused. To get around this latter problem, I added `global.screen.focus_default_window(global.get_current_time())` to `activate` function in `windowPreview.js`. To get around the former problem, I tried doing the same thing but when "leave-event" occurs to the taskbar. However, it seems that "leave-event" is never emitted when the panel is focused.

Another approach to addressing this problem that I tried is calling `this.sourceActor.grab_key_focus();` in `hoverOpen` of `windowPreview` and focusing window on `hoverClose.` However, this switching focus back and forth between window and panel whenever the previews pop up and hide causes flickering, the same cause as @franglais125's original solution I believe.

**Comment by jderose9** [comment] 2017-07-24 01:28
The flickering seems preferable to just not working. So I'd like to merge a fix if we can limit the flickering to VBox users.

**Comment by sw9** [comment] 2017-07-24 02:08
Even disregarding flickering, two addition problems remain. The active window will lose focus if you hover over the icon of another application. Also, if you hover over the icon of an application with no windows open, the current application highlight disappears temporarily.

**Comment by sw9** [comment] 2017-07-24 03:13
Well, looks like checking if the foreground app is VBox is the best of current options. Pushed code to my repository that does this. Any other apps to add to the blacklist? Is it just gnome boxes?

**Comment by jderose9** [comment] 2017-08-01 20:47
merged.. Thanks everyone!

**Closed by jderose9** 2017-08-01 20:47 UTC
Labels: bug
