### ISSUE TITLE
Various problems.. 

### ISSUE THREAD

**Issue by Warmuser** [jderose9/dash-to-panel#232] opened 2017-08-19 10:31 UTC
- I can't remove the favourites: https://www.youtube.com/watch?v=6bOtipp_Ji4
- I can't display the panel with plank on right/left: https://youtu.be/A1v4Xwt4QiY
- Sometimes conflict with Coverflow alt-tab: when I enable/disable these extension the panel becomes messy, the favourites disappear and the desktop seems to the point to freeze. I will report these issue also to the extension developer.

PS: I'm on Manjaro 17.0.2 GNOME 3.24.2

**Comment by jderose9** [comment] 2017-10-31 04:49
Hello there.. I'm sorry for the late reply.

> I can't remove the favourites: https://www.youtube.com/watch?v=6bOtipp_Ji4

I appreciate the video, but after watching a few times I am having trouble following exactly what issue you are having. I see you toggling the Favorites Menu extension but that extension seems to be unsupported after Gnome 3.20.

> I can't display the panel with plank on right/left: https://youtu.be/A1v4Xwt4QiY

So when you open plank the panel disappears? Is that right?

> Sometimes conflict with Coverflow alt-tab: when I enable/disable these extension the panel becomes messy, the favourites disappear and the desktop seems to the point to freeze. I will report these issue also to the extension developer.

A video and/or steps to reproduce would be great.

I'm  going to close this item because they really need to be each entered as separate issues so that they can be assigned to people and their status tracked individually. But, feel free to re-open issues for anything still outstanding with reproduction steps. Thank you, and sorry to be a pain!

**Closed by jderose9** 2017-10-31 04:49 UTC
