### ISSUE TITLE
prevent vertical scroll on the app icons

### ISSUE THREAD

**Issue by zagortenay333** [jderose9/dash-to-panel#22] opened 2017-01-11 23:09 UTC
Since the icons are in a scrollview container, they can actually be scrolled up/down.

**Comment by jderose9** [comment] 2017-01-12 03:32
Hi I can't reproduce this but I think it's a dupe of #18.

**Closed by jderose9** 2017-01-12 03:32 UTC
Labels: duplicate

**Comment by zagortenay333** [comment] 2017-01-12 10:13
Oh, sorry.
