### ISSUE TITLE
Check applications faster

### ISSUE THREAD

**Issue by AravK** [jderose9/dash-to-panel#133] opened 2017-04-18 14:14 UTC
There's a 1-2 second delay of updating current applications on the panel when I switch workspaces (w/ isolated workspaces on). Please add an option to speed this up. (If possible?)

**Comment by jderose9** [comment] 2017-04-25 00:45
Hi, is this the same as #96?

**Comment by jderose9** [comment] 2017-05-13 20:45
I'm going to close this one as I believe it is a duplicate of #92/#96. Thank you for reporting it!

**Closed by jderose9** 2017-05-13 20:45 UTC
Labels: duplicate
