### ISSUE TITLE
Crashes gnome-shell-extension-prefs

### ISSUE THREAD

**Issue by jbicha** [jderose9/dash-to-panel#151] opened 2017-05-10 17:34 UTC
Could you look into this? Have you already fixed the issue?

https://bugzilla.gnome.org/show_bug.cgi?id=782462

Here's the dates from the 3 crash reports:
Tuesday, May 9, 2017 04:57 UTC	3.24.1-0ubuntu1	Ubuntu 17.04	amd64
Tuesday, May 9, 2017 02:42 UTC	3.24.1-0ubuntu1	Ubuntu 17.04	amd64
Sunday, April 23, 2017 14:59 UTC	3.24.1-0ubuntu1	Ubuntu 17.04	amd64

**Comment by franglais125** [comment] 2017-05-11 00:40
@jbicha Do you know how to reproduce the error? I booted to Ubuntu 17.04, installed the extension, played around with it, but see no crashes.

**Comment by jbicha** [comment] 2017-05-11 00:53
Not really, no. I'm just forwarding on the errors that were reported to Ubuntu. I didn't personally experience the crash nor do I personally know anyone affected.

**Comment by ckrzen** [comment] 2017-05-11 15:51
FYI:  I thought this issue was related to my experience of a _seeming_-to-crash behavior in dash-to-panel, however -- I realized that if I turn-on:

Synchronize GNOME Shell extensions list:
If enabled, your GNOME Shell extensions list will be synchronized with your Google account.

in the Chrome extension called:

GNOME Shell integration

will remove extensions like this one if on one workstation, but not another due to what appears to be a one-way sync behavior in this Chrome extension.

Sorry to SPAM if this is not related.

**Comment by franglais125** [comment] 2017-05-11 15:59
@ckrzen If you are having issues with that Chrome extension, you can report them at https://github.com/nE0sIghT/chrome-gnome-shell-mirror/issues

This issue https://github.com/nE0sIghT/chrome-gnome-shell-mirror/issues/45 seems to be what you are describing, although it was closed some time ago.

**Comment by jderose9** [comment] 2017-05-14 03:00
@franglais125 I'm thinking this one may have been fixed by e52ccf632324acab4e56688e6b5a1e21465c71c2. That commit isn't out on e.g.o yet. What do you think?

**Comment by franglais125** [comment] 2017-05-14 03:13
That's actually the very first thing I thought of! But then dismissed as I assumed you had already uploaded a version with the fix to e.g.o. Perhaps not? :)

**Comment by jderose9** [comment] 2017-10-25 01:19
Closing this as I believe it was resolved..

**Closed by jderose9** 2017-10-25 01:19 UTC
Labels: bug
