### ISSUE TITLE
Panel formatting breaks after screensaver

### ISSUE THREAD

**Issue by hubslave** [jderose9/dash-to-panel#237] opened 2017-09-01 16:04 UTC
Hello, I probably found a little bug:

In normal case my panel looks like this:

![dashtopanel1](https://user-images.githubusercontent.com/29800872/29977956-85d0317a-8f3f-11e7-818f-b202f55c15d4.png)

Everythings works fine, until my computer is unused for a little while and screen locks, or screensaver is applied. After I "wake" my PC from screensaver, icons on the panel look like this:

![dashtopanel2](https://user-images.githubusercontent.com/29800872/29977958-88b9a006-8f3f-11e7-98d3-70aa4cd7bb4a.png)

They work, they respond as they should, just they are a little bit bigger and spaces between them are much wider. If i restart gnome shell they return to normal position.

I use Gnome 3.22 on HiDPi monitor

If you need any more information or testing please let me know :)

**Comment by pupyc** [comment] 2017-09-12 11:15
I also noticed this and it is really annoying, after the screen locks or turns off, the panel seems to reload itself when you unlock, and does some weird stuff, I noticed the margin between the icons increase and some other changes.

I was using gdm, but after some research I switched to lightdm and everything looks ok, but it is not the best solution, because all power-settings in gnome-control-settings do not work!.

**Comment by hubslave** [comment] 2017-09-12 11:21
Thank you for information... I would also prefer to stay at gdm. :/ Im just curious to know which power settings do not work with lightdm?

**Comment by pupyc** [comment] 2017-09-12 11:29
@hubslave automatic suspend does not affect lightdm, you can't lock the screen easily as in gdm, Im using a gnome extension called "Status menu buttons" to add lock and hibernate options, the screen does not turn off "blank" according to gnome-settings ... most of the settings do not apply to lightdm.

**Comment by hubslave** [comment] 2017-09-12 12:08
Thank you very much for clarification :)

**Comment by jderose9** [comment] 2017-09-12 19:42
Thanks for reporting this. Is it the same behavior described in #85?

**Comment by hubslave** [comment] 2017-09-14 21:33
Yes exactly the same behavior, sorry for duplicate I didnt noticed that thread. Gnome 3.22 on HiDPi monitor. I have no other addon installed except dash to panel. Except bigger spacing I also get these double shadows on running applications as TechnoSparks described:

![28023392-6900bf18-65c0-11e7-9f4e-ed007850e03e](https://user-images.githubusercontent.com/29800872/30456638-c4f11ea4-99a4-11e7-82a1-79c8c5cf07a9.png)

**Comment by hubslave** [comment] 2017-09-14 21:37
I cant reproduce this issue every time but most of the time the spaces are bigger after coming from screensaver... For example now I tried to manually lock the screen, went back to desktop and everything was fine. I restarted computer, did the same procedure and now the spaces are bigger 😕

**Comment by hubslave** [comment] 2017-09-14 21:39
I installed this addon directly from github, not from gnome-extensions

**Comment by pupyc** [comment] 2017-09-18 07:32
GDM isn't that good, I think it is all brecause of the GDM and the reload of the extensions.

Let's hope the new ubuntu patch for gdm will solve the issue. 

@jderose9 do you get this weird issue or it does not effect every one with the extension?

**Comment by jderose9** [comment] 2017-09-18 13:13
I'm going to close this one so we don't have dupes, but feel free to comment/subscribe to #85.

Unfortunately, I don't see this and I use GDM on Fedora on two different machines. If I could reproduce it, it would be a lot easier to track down the cause.

**Closed by jderose9** 2017-09-18 13:13 UTC
