### ISSUE TITLE
gnome 3.26 segfault in libgobject

### ISSUE THREAD

**Issue by vans163** [jderose9/dash-to-panel#246] opened 2017-09-20 00:39 UTC
When using multiple virtual workspaces and switching, there is a segfault.  Does not happen every time, so its probably a race condition.

```
Sep 19 20:33:33 gram kernel: acpi INT3400:00: Unsupported event [0x86]
Sep 19 20:33:33 gram pulseaudio[1569]: [pulseaudio] sink-input.c: Failed to create sink input: sink is suspended.
Sep 19 20:33:34 gram gnome-shell[2037]: st_widget_get_theme_node called on the widget [0x55d51397a480 StBin.workspace-thumbnail-indicator:first-child last-child] which is not in the stage
Sep 19 20:33:34 gram gnome-shell[2037]: st_widget_get_theme_node called on the widget [0x55d515e68700 StBin.workspace-thumbnail-indicator:first-child last-child] which is not in the stage
Sep 19 20:33:34 gram gnome-shell[2037]: st_widget_get_theme_node called on the widget [0x55d51955dd90 StBin.workspace-thumbnail-indicator:first-child last-child] which is not in the stage
Sep 19 20:33:35 gram gnome-shell[2037]: JS ERROR: TypeError: Shell.WindowTracker.get_default(...).focus_app is null
                                        thumbnailPreviewMenu<.hoverOpen@/home/user/.local/share/gnome-shell/extensions/dash-to-panel@jderose9.github.com/windowPreview.js:199:30
                                        wrapper@resource:///org/gnome/gjs/modules/lang.js:178:22

Sep 19 20:33:57 gram kernel: gnome-shell[2037]: segfault at 10900 ip 00007f63893cc622 sp 00007ffd741781f0 error 4 in libgobject-2.0.so.0.5400.0[7f6389397000+51000]


Sep 19 20:34:00 gram systemd-coredump[25242]: Core file was truncated to 2147483648 bytes.
Sep 19 20:34:00 gram abrt-dump-journal-core[1017]: Failed to obtain all required information from journald
Sep 19 20:34:01 gram systemd-coredump[25242]: Process 2037 (gnome-shell) of user 1000 dumped core.
                                              
                                              Stack trace of thread 2037:
                                              #0  0x00007f63893cc622 n/a (n/a)

```

**Comment by jderose9** [comment] 2017-10-12 01:31
Can you try latest master and see if it is any better?

**Comment by RichAyotte** [comment] 2017-10-18 00:51
I'm seeing the same error but don't have this extension.

```
[21992.619034] gnome-shell[25918]: segfault at 100000014 ip 00007f2f6a9a7cd1 sp 00007fff78565828 error 4 in libgobject-2.0.so.0.5400.1[7f2f6a972000+52000]
[22002.856739] gnome-shell[26433]: segfault at 100000014 ip 00007f347b682cd1 sp 00007ffe3660d6c8 error 4 in libgobject-2.0.so.0.5400.1[7f347b64d000+52000]
[22123.869473] gnome-shell[26627]: segfault at 447a0000 ip 00007fb907d61caf sp 00007fff92b307b8 error 4 in libgobject-2.0.so.0.5400.1[7fb907d2c000+52000]
```

**Comment by jderose9** [comment] 2017-10-18 02:27
Yeah, I fixed the error in the log prior to the segfault but given that the time difference I don't think they are actually related or that it is caused by this extension.

**Comment by jderose9** [comment] 2017-10-23 16:28
I'm going to close this as I believe it was adressed by #263, but feel free to post back if you experience it again. This is in the latest master and in v11 (which has been submitted but not yet approved by extensions.gnome.org)

**Closed by jderose9** 2017-10-23 16:28 UTC
