### ISSUE TITLE
Feature Request: Scroll to view Workspaces

### ISSUE THREAD

**Issue by Genius1237** [jderose9/dash-to-panel#54] opened 2017-01-31 16:52 UTC
Dash to Dock has an option by which scrolling on the dock will scroll to the workspace in the corresponding direction. Is it possible for that to be done here, where scrolling on the panel will switch workspaces.

**Comment by jderose9** [comment] 2017-02-06 04:43
Hi there.. I think this is a duplicate of #30.

Can you try the suggested solution and post back to that thread? 
https://extensions.gnome.org/extension/701/top-panel-workspace-scroll/

Thanks!

**Closed by jderose9** 2017-02-06 04:43 UTC
Labels: duplicate
